config/routes.rb
SpicyOrangesWebsite::Application.routes.draw do

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    get 'signup' => 'users#new', as: :signup
    get 'login' => 'sessions#new', as: :login
  end

  get 'logout' => 'sessions#destroy', as: :logout

  root 'pages#inicio'

  resources :users
  resources :sessions

  resources :pages
  resources :productos

  resources :uploads

  get 'inicio' => 'pages#inicio', as: :pages_inicio
  get 'empresa' => 'pages#empresa', as: :pages_empresa
  get 'trabajos' => 'pages#trabajos', as: :pages_trabajos
  get 'contacto' => 'pages#contacto', as: :pages_contacto

  

end

app/views/pages/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("1.jpg", :width => 700, :height => 350, :alt => "Sistemas ventanales", :class => "carousel_image") %>
      <div class="carousel-caption">
        <h3>Sistemas ventanales</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("2.jpg", :width => 700, :height => 350, :alt => "Puertas Protex", :class => "carousel_image") %>
      <div class="carousel-caption">
        <h3>Puertas Protex</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("3.jpg", :width => 700, :height => 350, :alt => "Ventanas y Puertas PVC", :class => "carousel_image") %>
      <div class="carousel-caption">
        <h3>Ventanas y Puertas PVC</h3>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Siguiente</span>
  </a>
</div>

app/views/pages/contacto.html.erb
<div id="content" class="row">
  <div class="col-md-4">
    <h2>Contactos</h2>

  </div>

  <div class="spicycontent col-md-8">
    <p>Nuestra empresa se encuentra en el barrio Las Condes. Pueden acercarse en oficina por dirección indicada. También puede comunicarse con nosotros por siguientes numeros de telefono o enviar un mensaje desde el formulario web.</p>

    <h3 class="panel-title">Telefonos:</h3>
    <br/>

    <p>
      <strong>Fijo</strong>: (56) 1234 5678<br/>
      <strong>Movil</strong>: (569) 1234 5678<br/>
      <strong>Email</strong>: info@alumart.cl
    </p>

    <p>
        Av. Apoquindo 3304, Oficina 465<br/>
        Las Condes, Santigo<br/>
        Chile (CP 12345)
    </p>

    <br/><br/>

    <%= form_tag sessions_path do %>
      <div class="form-group">
        <%= text_field_tag :name, "", :class => "form-control", :placeholder => "Ej. Juan Ignacio"  %>
      </div>

      <div class="form-group">
        <%= email_field_tag :email, "", :class => "form-control", :placeholder => "email@ejemplo.com" %>
      </div>

      <div class="form-group">
        <%= text_area_tag :message, "", :class => "form-control", :rows => 8  %>
      </div>

      <button type="submit" class="btn btn-success">Enviar mensaje</button>
    <% end %> 
  </div>

  <%= image_tag("feedbacks.png", :class => "spicysep col-md-12") %>
</div>

<div class="row">
  <div class="col-md-12">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6660.560885688618!2d-70.59682005106505!3d-33.41593217869651!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662cf156cf50c41%3A0xaf7ff4ecabd65d7a!2zQXBvcXVpbmRvIDMzMDAsIExhcyBDb25kZXMsIFJlZ2nDs24gTWV0cm9wb2xpdGFuYSwg0KfQuNC70Lg!5e0!3m2!1sru!2sar!4v1416586991869" width="940" height="300" frameborder="0" style="border:0"></iframe>
  </div>
</div>

app/views/pages/empresa.html.erb
<div id="content" class="row">
  <div class="col-md-4">
    <h2>Quienes somos</h2>
  </div>

  <div class="spicycontent col-md-8">
    <p>La empresa comienza su actividad en el año 1995 en Siberia Russia elaborando carpintería de madera y continuamos con la fabricación de aberturas de PVC, ante las exigencias del mundo moderno donde este material se posiciona cada vez mas alto.</p>

    <p>Alumart crea envolventes sostenibles para los edificios centradas en la gente y en sus necesidades en armonía con la naturaleza y tecnología. Cumple las más estrictas demandas de diseño, confort y seguridad sin renunciar a reducir las emisiones de CO2 con eficiencia energética y, por tanto, conservando los recursos naturales.</p>

    <p>Esta compañía con sus Divisiones de Aluminio y PVC ofrece productos a medida tanto para rehabilitación como nueva edificación, diseñados para abastecer las necesidades específicas de cada usuario en cualquier zona climática.</p>
  </div>

  <%= image_tag("feedbacks.png", :class => "spicysep col-md-12") %>
</div>

<div id="imagenav" class="row">
  <div class="col-md-4">
    <%= image_tag("aboutus-1.jpg", :class => "img-thumbnail", :width => 300) %>
  </div>

  <div class="col-md-4">
    <%= image_tag("aboutus-2.jpg", :class => "img-thumbnail", :width => 300) %>
  </div>

   <div class="col-md-4">
    <%= image_tag("aboutus-3.jpg", :class => "img-thumbnail", :width => 300) %>
  </div> 
</div>

app/views/pages/inicio.html.erb
<div id="banners" class="row">
  <div class="col-md-12">
    <%= render "carousel" %>
  </div>
</div>

<div id="feedbacks" class="row">
  <div class="col-md-12">
      <h3><em>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</em></h3>
  </div>
  <%= image_tag("feedbacks.png") %>
</div>

<div id="products" class="row">
  <div class="col-md-4">
  <h2>Ventanas PVC</h2>

  <p><%= sanitize(truncate(Producto.find(3).description, :ommision => "... Leer mas", :length => 210)) %></p>

  <p class="centered"><%= link_to image_tag("button-go.png"), producto_path(3) %></p>
  </div> 

  <div class="col-md-4">
  <h2>Puertas Protex</h2>

  <p><%= sanitize(truncate(Producto.find(4).description, :ommision => "... Leer mas", :length => 210)) %></p>

  <p class="centered"><%= link_to image_tag("button-go.png"), producto_path(4) %></p>
  </div> 

  <div class="col-md-4">
  <h2>Shower Room</h2>

  <p><%= sanitize(truncate(Producto.find(1).description, :ommision => "... Leer mas", :length => 210)) %></p>

  <p class="centered"><%= link_to image_tag("button-go.png"), producto_path(1) %></p>
  </div>     
</div>

app/views/pages/trabajos.html.erb
<div id="content" class="row">
  <div class="spicycontent col-md-12">
  <h2>Nuestros Trabajos</h2>


    <div class="row">
    <% @uploads.each do |upload| %>
      <div class="col-xs-6 col-md-3">
         <%= image_tag(upload.uploaded_file(:medium), class: "img-thumbnail")  %>
      </div>
    <% end %>
    </div> 

  </div>

  <%= image_tag("feedbacks.png", :class => "spicysep col-md-12") %>
</div>