config/routes.rb
SpicyOrangesWebsite::Application.routes.draw do

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    get 'signup' => 'users#new', as: :signup
    get 'login' => 'sessions#new', as: :login
  end

  get 'logout' => 'sessions#destroy', as: :logout

  root 'pages#inicio'

  resources :users
  resources :sessions

  resources :pages
  resources :productos

  resources :uploads

  get 'inicio' => 'pages#inicio', as: :pages_inicio
  get 'empresa' => 'pages#empresa', as: :pages_empresa
  get 'trabajos' => 'pages#trabajos', as: :pages_trabajos
  get 'contacto' => 'pages#contacto', as: :pages_contacto

  

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
  validates :slug, presence: true
  validates :description, presence: true
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  add_breadcrumb "Inicio", :root_path, :options => { :title => "Inicio" }

  def index
    @productos = Producto.all
    add_breadcrumb "Listado de productos", ''
  end

  def new
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    @producto = Producto.new

    add_breadcrumb "Listado de productos", productos_path
    add_breadcrumb "Agregar nuevo producto", new_producto_path, :options => { :title => "Agregar Producto" }
  end

  def create
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    #render plain: params[:productos].inspect
    @producto = Producto.new(producto_params)
   
    if @producto.save
      redirect_to @producto
    else
      render 'new'
    end     
  end

  def edit
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    @producto = Producto.find(params[:id])

    add_breadcrumb "Listado de productos", productos_path
    add_breadcrumb "Redactar producto", new_producto_path, :options => { :title => "Redactar Producto" }
  end

  def update
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    @producto = Producto.find(params[:id])
   
    if @producto.update(producto_params)
      redirect_to @producto
    else
      render 'edit'
    end 
  end

  def show
    @producto = Producto.find(params[:id])

    add_breadcrumb "Producto: #{@producto.title} ", producto_path(@producto.id), :options => { :title => @producto.title }
  end

  def destroy
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?
    
    @producto = Producto.find(params[:id])
    @producto.destroy
   
    redirect_to productos_path
  end

private
  def producto_params
    params.require(:producto).permit(:title, :slug, :description)
  end  
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for @producto do |f| %>
  <% if @producto.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@producto.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @producto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Titulo de producto" %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :slug, "Slug para url (sin espacios)" %>
    <%= f.text_field :slug, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Texto" %>
    <%= f.text_area :description, :class => "wysihtml5 form-control" %>
  </div>
 
  <button type="submit" class="btn btn-success">Agregar producto</button>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/productos/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<div id="content" class="row">
  <div class="col-md-12">

  <h2>Listado de productos</h2>

  <table class="table table-striped">
  <% @productos.each do |producto| %>
    <tr>
      <td width="70%"><strong><%= producto.title %></strong></td>
      <td><%= link_to 'Ver', producto_path(producto.id), :class => "btn btn-primary" %></td>
      <td><%= link_to 'Redactar', edit_producto_path(producto.id),  :class => "btn btn-warning" %></td>
      <td><%= link_to 'Eliminar', producto_path(producto.id), :class => "btn btn-danger", method: :delete, data: { confirm: 'Estas seguro?' } %></td>
    </tr>
  <% end %>
    
  </table>

  <div class="alert alert-info" role="alert">
    <%= link_to 'Agregar nuevo producto', new_producto_path, :class => "alert-link" %>
  </div>
  </div>
</div>

app/views/productos/new.html.erb
<div id="content" class="row">
  <div class="col-md-9">

  <h2>Agregar nuevo producto</h2>

  <%= render 'form' %>

  </div>
</div>

app/views/productos/show.html.erb
<div id="content" class="row">
  <div class="col-md-4">
    <h2>Nuestros Productos</h2>

    <div id="sidebar" class="list-group">
    <% product_list.each do |p| %>
      <%= link_to p.title, producto_path(p.id), :class => "list-group-item #{active_link_to_class(producto_path(p.id), :active => :inclusive)}" %>
    <% end %>
    </div>
  </div>

  <div class="spicycontent col-md-8">
  <%= @producto.description.html_safe %>
  </div>

  <%= image_tag("feedbacks.png", :class => "spicysep col-md-12") %>
</div>