config/routes.rb
SpicyOrangesWebsite::Application.routes.draw do

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    get 'signup' => 'users#new', as: :signup
    get 'login' => 'sessions#new', as: :login
  end

  get 'logout' => 'sessions#destroy', as: :logout

  root 'pages#inicio'

  resources :users
  resources :sessions

  resources :pages
  resources :productos

  resources :uploads

  get 'inicio' => 'pages#inicio', as: :pages_inicio
  get 'empresa' => 'pages#empresa', as: :pages_empresa
  get 'trabajos' => 'pages#trabajos', as: :pages_trabajos
  get 'contacto' => 'pages#contacto', as: :pages_contacto

  

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :uploaded_file, styles: { original: "1500x1500>", large: "1000x1000>", medium: "500x500>", small: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :uploaded_file, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?
  end

  # POST /uploads
  # POST /uploads.json
  def create
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    @upload = Upload.create(upload_params)
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?

    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    redirect_to root_path, notice: "Area protegida. Requiere login!" if current_user.nil?
    
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:uploaded_file)
      #params[:upload].permit(:uploaded_file)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= form_for(@upload, html: { multipart: true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% @upload.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions form-group">
    <h4><%= f.label :uploaded_file, "Seleccionar archivos" %></h4>

    <p><%= f.file_field :uploaded_file, multiple: true, name: 'upload[uploaded_file]' %></p>

    <p><%= f.submit "Agregar imagenes", :class => "btn btn-success" %></p>
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="progress-bar bar" style="width: 0%"></div></div></div></script>

app/views/uploads/_upload.html.erb
<%= image_tag(@upload.uploaded_file(:small), class: 'thumb')  %>

app/views/uploads/create.js.erb
<% if @upload.new_record? %>
  alert('Error');
<% else %>
  if ($('h1') !== undefined) {
    $('h1').append("<%=j render partial: 'uploads/upload', locals: { upload: @upload } %>");
  }
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div id="content" class="row">
  <div class="col-md-4">
    <div id="sidebar" class="list-group">
      <h4>Administrador de imagenes</h4>

      <%= link_to "Agregar imagenes", new_upload_path, :class => "list-group-item", data: { no_turbolink: true } %>
      <%= link_to 'Listado de imagenes', uploads_path,  :class => "list-group-item" %>
    </div>
  </div>

  <div class="spicycontent col-md-8">

  <div class="row">
  <% @uploads.each do |upload| %>
    <div class="col-xs-6 col-md-3">
       <%= image_tag(upload.uploaded_file(:medium), class: "img-thumbnail")  %>
      <%= link_to 'Redactar', edit_upload_path(upload) %>
      <%= link_to 'Eliminar', upload, method: :delete, data: { confirm: 'Estas seguro?' } %>       
    </div>
  <% end %>
  </div> 

  </div>

  <%= image_tag("feedbacks.png", :class => "spicysep col-md-12") %>
</div

app/views/uploads/new.html.erb
<div id="content" class="row">
  <div class="col-md-4">
    <div id="sidebar" class="list-group">
      <h4>Administrador de imagenes</h4>

      <%= link_to "Agregar imagenes", new_upload_path, :class => "list-group-item", data: { no_turbolink: true } %>
      <%= link_to 'Listado de imagenes', uploads_path,  :class => "list-group-item" %>
    </div>
  </div>

  <div class="spicycontent col-md-8">

  <%= render 'form' %>
  
  </div>

  <%= image_tag("feedbacks.png", :class => "spicysep col-md-12") %>
</div

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<%= render 'upload' %>
<br />

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>