config/routes.rb
SpicyOrangesWebsite::Application.routes.draw do

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    get 'signup' => 'users#new', as: :signup
    get 'login' => 'sessions#new', as: :login
  end

  get 'logout' => 'sessions#destroy', as: :logout

  root 'pages#inicio'

  resources :users
  resources :sessions

  resources :pages
  resources :productos

  resources :uploads

  get 'inicio' => 'pages#inicio', as: :pages_inicio
  get 'empresa' => 'pages#empresa', as: :pages_empresa
  get 'trabajos' => 'pages#trabajos', as: :pages_trabajos
  get 'contacto' => 'pages#contacto', as: :pages_contacto

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :require_login

  def product_list
    @productos_links = Producto.all
  end
  helper_method :product_list


private
  def current_user
    warden.user
  end
  helper_method :current_user

  def warden
    env['warden']
  end

#  def require_login
#   unless current_user.nil?
#      flash[:error] = "You must be logged in to access this section"
#      redirect_to login_url # halts request cycle
#    end
#  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/views/application/_breadcrumbs.html.erb
<div id="crummybread" class="row">
<ol class="breadcrumb">
  <%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>  
</div>

app/views/application/_footer.html.erb
<div id="footer" class="container-fluid">
  <div class="row">

  <div class="container">
  <div class="row fcontent">

    <div class="col-md-2">
      <%= image_tag("logo-alumart.png", :alt => "Alumart Empresa", :width => 75, :title => "Empresa Alumart") %>
    </div>

    <div class="col-md-6 vcenter">
    <p>
      <%= link_to "Inicio", pages_inicio_path %> <span>|</span>
      <%= link_to "Quienes Somos", pages_empresa_path %> <span>|</span>
      <%= link_to "Trabajos", pages_trabajos_path %> <span>|</span>
      <%= link_to "Contacto", pages_contacto_path %>
    </p>
    </div>

    <div class="col-md-4 vcenter">
    <p class="text-right">
    <% if current_user %>
      <%= link_to "Salir", logout_path %>
      <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
    <% else %>
      <%= link_to "Entrar", login_path %>
    <% end %>
    </p>
    </div>

  </div> 
  </div>

  </div>
</div>

app/views/application/_header.html.erb
<div id="header" class="row">
  <div class="col-md-4">
    <%= link_to image_tag("logo-alumart.png", :alt => "Alumart Logo", :width => 130, :title => "Logo Alumart"), root_path %>
  </div>

  <div class="col-md-8">
    <ul id="menubar" class="nav nav-pills">
      <li class="active"><%= link_to "Inicio", root_path %></li>
      <li><%= link_to "Quienes Somos", pages_empresa_path %></li>

      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Productos <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
        <% product_list.each do |p| %>
          <li><%= link_to p.title, producto_path(p.id) %></li>
        <% end %>
        </ul>
      </li>

      <li><%= link_to "Trabajos", pages_trabajos_path %></li>
      <li><%= link_to "Contacto", pages_contacto_path %></li>
    </ul>
  </div>    
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
 
    <div class="navbar-header">
     <%= link_to image_tag("a.png", :alt => "Alumart Brand", :title => "Logo Alumart", :width => 24), root_path, :class => "navbar-brand" %>
    </div>   


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "Ver productos", productos_path %></li>
        <li><%= link_to "Agregar producto", new_producto_path %></li>
        <li><%= link_to 'Agregar Fotos en Trabajos', new_upload_path, data: { no_turbolink: true } %></li>
      </ul>

      <p class="navbar-text navbar-right">Ingresado como <strong><%= current_user.email %></strong>. <%= link_to "Salir", logout_path %></p>      
    </div>
  </div>
</nav>